name = "portfolio"
main = ".vercel/output/functions/[[path]].func/index.js"
compatibility_date = "2025-08-02"
[site]
bucket = ".vercel/output/static"

[build]
command = "npm install && npx @cloudflare/next-on-pages"
