name: Screenshot and GIF Generator

on: [push, pull_request]

jobs:
  screenshot-and-gif:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper timestamps
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ash-portfolio/package-lock.json
      
      - name: Install dependencies
        run: |
          cd ash-portfolio
          npm ci
            
      - name: Install screenshot and GIF tools
        run: |
          cd ash-portfolio
          npm install -g puppeteer gifski
          mkdir -p images
      
      - name: Start Next.js app and take screenshot
        run: |
          # Start the Next.js app in the background
          cd ash-portfolio
          npm run start &
          
          # Wait for the app to start
          sleep 10

      - name: Run Puppeteer to take screenshot
        working-directory: ./ash-portfolio
        run: |
          node screenshot.js

      - name: Commit screenshot
        working-directory: ./ash-portfolio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add screenshot*.png
          git commit -m "Add screenshot [skip ci]"
          git push origin HEAD:${{ github.ref }}
